version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27117:27017
  node:
    build: .
    environment:
      - ENV=docker
      - NODE_ENV=dev
    volumes:
      - .:/var/app/
      - /var/app/node_modules
    ports:
      - 8082:8082

    command: bash -c "sleep 5 && npm run dev"

    depends_on:
      - mongo